import type { Release } from "./data";

export const DISCOGRAPHY: Release[] = [
  {
    id: "everyday",
    title: "Everyday",
    artist: "Raskal",
    year: "2025",
    genre: "EP",
    releaseType: "EP",
    description: "Everyday by Raskal — a ep release on Southern Exposure Music.",
    image: "/images/releases/everyday.jpg",
    imageAlt: "Everyday by Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/4tEY5iBCu1K0NQxtDyFa4L",
    spotifyUrl: "https://open.spotify.com/album/4tEY5iBCu1K0NQxtDyFa4L",
  },
  {
    id: "high-emotion",
    title: "High Emotion",
    artist: "Bozzy, False Peaks",
    year: "2025",
    genre: "Single",
    releaseType: "SINGLE",
    description: "High Emotion by Bozzy, False Peaks — a single release on Southern Exposure Music.",
    image: "/images/releases/high-emotion.jpg",
    imageAlt: "High Emotion by Bozzy, False Peaks — Southern Exposure Music release artwork",
    spotifyId: "album/0PrdP8rr5Y1g6Hbh7HpEGi",
    spotifyUrl: "https://open.spotify.com/album/0PrdP8rr5Y1g6Hbh7HpEGi",
  },
  {
    id: "this-moment",
    title: "This Moment",
    artist: "Aidan Rolfe",
    year: "2025",
    genre: "Single",
    releaseType: "SINGLE",
    description: "This Moment by Aidan Rolfe — a single release on Southern Exposure Music.",
    image: "/images/releases/this-moment.jpg",
    imageAlt: "This Moment by Aidan Rolfe — Southern Exposure Music release artwork",
    spotifyId: "album/3g8vEltouCQg1qmS6fkxsg",
    spotifyUrl: "https://open.spotify.com/album/3g8vEltouCQg1qmS6fkxsg",
  },
  {
    id: "arcane",
    title: "Arcane",
    artist: "Raskal",
    year: "2024",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Arcane by Raskal — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0230afa164fe53a8b7483143a6",
    imageAlt: "Arcane by Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/28zMQQgdWT8YXykZ8MC9kt",
    spotifyUrl: "https://open.spotify.com/album/28zMQQgdWT8YXykZ8MC9kt",
  },
  {
    id: "handle-this",
    title: "Handle This",
    artist: "Aidan Rolfe",
    year: "2024",
    genre: "EP",
    releaseType: "EP",
    description: "Handle This by Aidan Rolfe — a ep release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02837a2df81bf31c4d55e18179",
    imageAlt: "Handle This by Aidan Rolfe — Southern Exposure Music release artwork",
    spotifyId: "album/4FRmiFJuZoxxKyEIYfOilY",
    spotifyUrl: "https://open.spotify.com/album/4FRmiFJuZoxxKyEIYfOilY",
  },
  {
    id: "hot-as-hell",
    title: "Hot as Hell",
    artist: "Aidan Rolfe",
    year: "2024",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Hot as Hell by Aidan Rolfe — a single release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02a40b5a753b8119f2b65f35a3",
    imageAlt: "Hot as Hell by Aidan Rolfe — Southern Exposure Music release artwork",
    spotifyId: "album/3hkJDNxEzBQJwzC7wea4Uy",
    spotifyUrl: "https://open.spotify.com/album/3hkJDNxEzBQJwzC7wea4Uy",
  },
  {
    id: "how-not-to-write-a-love-song",
    title: "How Not to Write a Love Song",
    artist: "Aidan Rolfe",
    year: "2024",
    genre: "EP",
    releaseType: "EP",
    description: "How Not to Write a Love Song by Aidan Rolfe — a ep release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e024fb8f3fa65f5f6415b08207d",
    imageAlt: "How Not to Write a Love Song by Aidan Rolfe — Southern Exposure Music release artwork",
    spotifyId: "album/3cEBjwjGn1ffYbDKNGxbm5",
    spotifyUrl: "https://open.spotify.com/album/3cEBjwjGn1ffYbDKNGxbm5",
  },
  {
    id: "lucid-dream",
    title: "Lucid Dream",
    artist: "Raskal (US), Raskal",
    year: "2024",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Lucid Dream by Raskal (US), Raskal — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e020e446959a45e9b546a73b768",
    imageAlt: "Lucid Dream by Raskal (US), Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/5W2oRVJJW79wsMpMBxRYs6",
    spotifyUrl: "https://open.spotify.com/album/5W2oRVJJW79wsMpMBxRYs6",
  },
  {
    id: "obscure",
    title: "Obscure",
    artist: "Nhexis",
    year: "2024",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Obscure by Nhexis — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0277ee3ea1253975c666ee957e",
    imageAlt: "Obscure by Nhexis — Southern Exposure Music release artwork",
    spotifyId: "album/0dccnnPQzQtckm32AwxNNf",
    spotifyUrl: "https://open.spotify.com/album/0dccnnPQzQtckm32AwxNNf",
  },
  {
    id: "recovery",
    title: "Recovery",
    artist: "Aidan Rolfe",
    year: "2024",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Recovery by Aidan Rolfe — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02d3c0241b8df7b0c1711dc6cd",
    imageAlt: "Recovery by Aidan Rolfe — Southern Exposure Music release artwork",
    spotifyId: "album/7vQn9KqPLx86t28CYkKgkh",
    spotifyUrl: "https://open.spotify.com/album/7vQn9KqPLx86t28CYkKgkh",
  },
  {
    id: "shopper",
    title: "Shopper",
    artist: "Fried Coffee",
    year: "2024",
    genre: "EP",
    releaseType: "EP",
    description: "Shopper by Fried Coffee — a ep release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e028c5166f96337bbbfec4756d2",
    imageAlt: "Shopper by Fried Coffee — Southern Exposure Music release artwork",
    spotifyId: "album/0i6vS9rThatiJIOF5CejES",
    spotifyUrl: "https://open.spotify.com/album/0i6vS9rThatiJIOF5CejES",
  },
  {
    id: "stalker-vibes",
    title: "Stalker Vibes",
    artist: "Raskal",
    year: "2024",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Stalker Vibes by Raskal — a single release on Southern Exposure Music.",
    image: "/images/releases/stalker-vibes.jpg",
    imageAlt: "Stalker Vibes by Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/5syVONFeINi06dDeFOHmq2",
    spotifyUrl: "https://open.spotify.com/album/5syVONFeINi06dDeFOHmq2",
  },
  {
    id: "consciousness",
    title: "Consciousness",
    artist: "S.A.C.",
    year: "2023",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Consciousness by S.A.C. — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0272faeab1503773e7bbc4b027",
    imageAlt: "Consciousness by S.A.C. — Southern Exposure Music release artwork",
    spotifyId: "album/1ujhlnmbx7dGh2Gmtin8fk",
    spotifyUrl: "https://open.spotify.com/album/1ujhlnmbx7dGh2Gmtin8fk",
  },
  {
    id: "human-touch",
    title: "Human Touch",
    artist: "Raskal",
    year: "2023",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Human Touch by Raskal — a single release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02a766f60a1fb28ea6a8ad9a69",
    imageAlt: "Human Touch by Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/6INqR7LvFWBtsoHWs5wMfJ",
    spotifyUrl: "https://open.spotify.com/album/6INqR7LvFWBtsoHWs5wMfJ",
  },
  {
    id: "manic",
    title: "Manic",
    artist: "Aidan Rolfe",
    year: "2023",
    genre: "EP",
    releaseType: "EP",
    description: "Manic by Aidan Rolfe — a ep release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02b9f7d7c8b2c1f1cf03912417",
    imageAlt: "Manic by Aidan Rolfe — Southern Exposure Music release artwork",
    spotifyId: "album/55W2ZWD0gQLu6e1hoR5D9O",
    spotifyUrl: "https://open.spotify.com/album/55W2ZWD0gQLu6e1hoR5D9O",
  },
  {
    id: "neurodivergent",
    title: "Neurodivergent",
    artist: "Aidan Rolfe",
    year: "2023",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Neurodivergent by Aidan Rolfe — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e0249af57f697534665dd5564de",
    imageAlt: "Neurodivergent by Aidan Rolfe — Southern Exposure Music release artwork",
    spotifyId: "album/7FrJMJJ2R0B6Qoi9AQocbK",
    spotifyUrl: "https://open.spotify.com/album/7FrJMJJ2R0B6Qoi9AQocbK",
  },
  {
    id: "alteration",
    title: "Alteration",
    artist: "18 East, Mike Turing",
    year: "2022",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Alteration by 18 East, Mike Turing — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a052cbfa13df4824255d8950",
    imageAlt: "Alteration by 18 East, Mike Turing — Southern Exposure Music release artwork",
    spotifyId: "album/2Hw3S6RwGDe9Gr7imhSDrn",
    spotifyUrl: "https://open.spotify.com/album/2Hw3S6RwGDe9Gr7imhSDrn",
  },
  {
    id: "for-your-mind",
    title: "For Your Mind",
    artist: "Raskal (US), Raskal",
    year: "2022",
    genre: "Single",
    releaseType: "SINGLE",
    description: "For Your Mind by Raskal (US), Raskal — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02fc81dd7ec07c835d8f2f8b58",
    imageAlt: "For Your Mind by Raskal (US), Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/4H7fVvw2dCaDu7nBODz4FW",
    spotifyUrl: "https://open.spotify.com/album/4H7fVvw2dCaDu7nBODz4FW",
  },
  {
    id: "we-are-in-control",
    title: "We Are in Control",
    artist: "Raskal",
    year: "2022",
    genre: "Single",
    releaseType: "SINGLE",
    description: "We Are in Control by Raskal — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e020a86c1360e1308ea89867937",
    imageAlt: "We Are in Control by Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/12gV7I6Gb3UKUWAjuVwVLE",
    spotifyUrl: "https://open.spotify.com/album/12gV7I6Gb3UKUWAjuVwVLE",
  },
  {
    id: "taleh-elohim",
    title: "Taleh Elohim",
    artist: "James Nesbit, CKsimon",
    year: "2020",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Taleh Elohim by James Nesbit, CKsimon — a single release on Southern Exposure Music.",
    image: "/images/releases/taleh-elohim.jpg",
    imageAlt: "Taleh Elohim by James Nesbit, CKsimon — Southern Exposure Music release artwork",
    spotifyId: "album/2tMT3477A1zxPJhcixOreK",
    spotifyUrl: "https://open.spotify.com/album/2tMT3477A1zxPJhcixOreK",
  },
  {
    id: "troubled-nights",
    title: "Troubled Nights",
    artist: "Raskal (US), Raskal",
    year: "2020",
    genre: "EP",
    releaseType: "EP",
    description: "Troubled Nights by Raskal (US), Raskal — a ep release on Southern Exposure Music.",
    image: "/images/releases/troubled-nights.jpg",
    imageAlt: "Troubled Nights by Raskal (US), Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/5u6CTGGanOxe8zY9rwAFxE",
    spotifyUrl: "https://open.spotify.com/album/5u6CTGGanOxe8zY9rwAFxE",
  },
  {
    id: "droid-love",
    title: "Droid Love",
    artist: "Raskal (US), Ralph & Louie",
    year: "2019",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Droid Love by Raskal (US), Ralph & Louie — a single release on Southern Exposure Music.",
    image: "/images/releases/droid-love.jpg",
    imageAlt: "Droid Love by Raskal (US), Ralph & Louie — Southern Exposure Music release artwork",
    spotifyId: "album/0d6CiCjGAXFFYfy5GJYVym",
    spotifyUrl: "https://open.spotify.com/album/0d6CiCjGAXFFYfy5GJYVym",
  },
  {
    id: "the-vision",
    title: "The Vision",
    artist: "Reiche",
    year: "2019",
    genre: "Single",
    releaseType: "SINGLE",
    description: "The Vision by Reiche — a single release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02c591dfb632461d813a04172a",
    imageAlt: "The Vision by Reiche — Southern Exposure Music release artwork",
    spotifyId: "album/5ZXIQSURqVYe2AJCHHRX8W",
    spotifyUrl: "https://open.spotify.com/album/5ZXIQSURqVYe2AJCHHRX8W",
  },
  {
    id: "carillon",
    title: "Carillon",
    artist: "Monoteck",
    year: "2018",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Carillon by Monoteck — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02b45fe2f5d4b96d963df07ae0",
    imageAlt: "Carillon by Monoteck — Southern Exposure Music release artwork",
    spotifyId: "album/3rRBHT1oWjfznLgZkUrBlv",
    spotifyUrl: "https://open.spotify.com/album/3rRBHT1oWjfznLgZkUrBlv",
  },
  {
    id: "chk-this-out",
    title: "Chk This Out",
    artist: "Beau3tiful",
    year: "2018",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Chk This Out by Beau3tiful — a single release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0271be35fb1a9cc8570032deb3",
    imageAlt: "Chk This Out by Beau3tiful — Southern Exposure Music release artwork",
    spotifyId: "album/2SgCMuDrVWdGopAeCoffRW",
    spotifyUrl: "https://open.spotify.com/album/2SgCMuDrVWdGopAeCoffRW",
  },
  {
    id: "east-meets-west",
    title: "East Meets West",
    artist: "Reiche",
    year: "2018",
    genre: "Single",
    releaseType: "SINGLE",
    description: "East Meets West by Reiche — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e024ef09b3ba76ef9b3c67c80a5",
    imageAlt: "East Meets West by Reiche — Southern Exposure Music release artwork",
    spotifyId: "album/2OfuvfPNnEybwXq9jnGGo7",
    spotifyUrl: "https://open.spotify.com/album/2OfuvfPNnEybwXq9jnGGo7",
  },
  {
    id: "havana",
    title: "Havana",
    artist: "Ralph & Louie, Lunna",
    year: "2018",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Havana by Ralph & Louie, Lunna — a single release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0280d95f8fd05630828c2d9a2b",
    imageAlt: "Havana by Ralph & Louie, Lunna — Southern Exposure Music release artwork",
    spotifyId: "album/1VUcLXI8Z1Ouw8GUmLfR5M",
    spotifyUrl: "https://open.spotify.com/album/1VUcLXI8Z1Ouw8GUmLfR5M",
  },
  {
    id: "i-get-on",
    title: "I Get On",
    artist: "ThePat",
    year: "2018",
    genre: "EP",
    releaseType: "EP",
    description: "I Get On by ThePat — a ep release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02ed9ef98fe673c36d237ce90b",
    imageAlt: "I Get On by ThePat — Southern Exposure Music release artwork",
    spotifyId: "album/0SxcjiXYM7Tc20NU3H9MUX",
    spotifyUrl: "https://open.spotify.com/album/0SxcjiXYM7Tc20NU3H9MUX",
  },
  {
    id: "let-me-in",
    title: "Let Me In",
    artist: "Raskal (US), Raskal",
    year: "2018",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Let Me In by Raskal (US), Raskal — a single release on Southern Exposure Music.",
    image: "/images/releases/let-me-in.jpg",
    imageAlt: "Let Me In by Raskal (US), Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/7GX9moeMVC4Ock3KJ7PLzf",
    spotifyUrl: "https://open.spotify.com/album/7GX9moeMVC4Ock3KJ7PLzf",
  },
  {
    id: "southern-exposure-s-hidden-universe-vol-1",
    title: "Southern Exposure's Hidden Universe, Vol. 1",
    artist: "Various Artists",
    year: "2018",
    genre: "Compilation",
    releaseType: "COMPILATION",
    description: "Southern Exposure's Hidden Universe, Vol. 1 by Various Artists — a compilation release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02614b8d36516eb30f93e4ba33",
    imageAlt: "Southern Exposure's Hidden Universe, Vol. 1 by Various Artists — Southern Exposure Music release artwork",
    spotifyId: "album/4NNNLpHanKOHs68s0Zof99",
    spotifyUrl: "https://open.spotify.com/album/4NNNLpHanKOHs68s0Zof99",
  },
  {
    id: "directive-prime",
    title: "Directive Prime",
    artist: "Raskal (US), Raskal",
    year: "2017",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Directive Prime by Raskal (US), Raskal — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e025160bd212b3699af383c8ba2",
    imageAlt: "Directive Prime by Raskal (US), Raskal — Southern Exposure Music release artwork",
    spotifyId: "album/3dNjaoFHTAuMeNFXKCjJWh",
    spotifyUrl: "https://open.spotify.com/album/3dNjaoFHTAuMeNFXKCjJWh",
  },
  {
    id: "increase-the-frequency",
    title: "Increase the Frequency",
    artist: "Raskal, Tonal Grooves",
    year: "2017",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Increase the Frequency by Raskal, Tonal Grooves — a single release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02c896ec72e6d06701db8b8fab",
    imageAlt: "Increase the Frequency by Raskal, Tonal Grooves — Southern Exposure Music release artwork",
    spotifyId: "album/2LQBmoX7myZXEXkBlyGQaP",
    spotifyUrl: "https://open.spotify.com/album/2LQBmoX7myZXEXkBlyGQaP",
  },
  {
    id: "no-way-out",
    title: "No Way Out",
    artist: "Reiche",
    year: "2017",
    genre: "Single",
    releaseType: "SINGLE",
    description: "No Way Out by Reiche — a single release on Southern Exposure Music.",
    image: "https://image-cdn-fa.spotifycdn.com/image/ab67616d00001e02a0c257794ce723f9a1941942",
    imageAlt: "No Way Out by Reiche — Southern Exposure Music release artwork",
    spotifyId: "album/1yqtUn6CynOs6xrKGSBSbu",
    spotifyUrl: "https://open.spotify.com/album/1yqtUn6CynOs6xrKGSBSbu",
  },
  {
    id: "through-the-motions",
    title: "Through the Motions",
    artist: "Ralph & Louie",
    year: "2017",
    genre: "Single",
    releaseType: "SINGLE",
    description: "Through the Motions by Ralph & Louie — a single release on Southern Exposure Music.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02466db1d81de291728765ff28",
    imageAlt: "Through the Motions by Ralph & Louie — Southern Exposure Music release artwork",
    spotifyId: "album/1MGPzUEsbDzdjOv1C14Hxr",
    spotifyUrl: "https://open.spotify.com/album/1MGPzUEsbDzdjOv1C14Hxr",
  },
  {
    id: "freeborn-air",
    title: "Freeborn Air",
    artist: "The Lawn Darts",
    year: "2015",
    genre: "Indie / Alternative",
    releaseType: "ALBUM",
    description:
      "The Lawn Darts' full-length album on Southern Exposure Music — indie alternative songwriting and live-band energy from the SEM catalog.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0233c3f384dada89c730d22e39",
    imageAlt: "Freeborn Air by The Lawn Darts — Southern Exposure Music release artwork",
    spotifyId: "album/08EW1r47Mt3VT0fQATLrKt",
    spotifyUrl: "https://open.spotify.com/album/08EW1r47Mt3VT0fQATLrKt",
  },
  {
    id: "on-a-clear-day",
    title: "On a Clear Day",
    artist: "Lisle Crowley",
    year: "2015",
    genre: "Singer-Songwriter",
    releaseType: "ALBUM",
    description:
      "Lisle Crowley's album on Southern Exposure Music — intimate singer-songwriter storytelling and acoustic-driven arrangements.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e02712dd8f4e8892e63254a1d71",
    imageAlt: "On a Clear Day by Lisle Crowley — Southern Exposure Music release artwork",
    spotifyId: "album/6A0Tp2LQqkrkAbQSjUTYSN",
    spotifyUrl: "https://open.spotify.com/album/6A0Tp2LQqkrkAbQSjUTYSN",
  },
  {
    id: "o-come-all-ye-faithful",
    title: "O Come All Ye Faithful",
    artist: "High Desert Duo",
    year: "2013",
    genre: "Holiday / Acoustic",
    releaseType: "ALBUM",
    description:
      "High Desert Duo's holiday album on Southern Exposure Music — acoustic seasonal music from the early SEM catalog.",
    image: "https://image-cdn-ak.spotifycdn.com/image/ab67616d00001e0272eb9e341c4d5996514ba055",
    imageAlt: "O Come All Ye Faithful by High Desert Duo — Southern Exposure Music release artwork",
    spotifyId: "album/73vbHk4XvKZFJxBVJuKdHM",
    spotifyUrl: "https://open.spotify.com/album/73vbHk4XvKZFJxBVJuKdHM",
  },
];

export const FEATURED_RELEASE_IDS = [
  "this-moment",
  "everyday",
  "high-emotion",
  "stalker-vibes",
  "troubled-nights",
  "droid-love",
  "let-me-in",
  "taleh-elohim",
] as const;